version: "3.8"

services:
  client:
    build:
      context: client.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: server.dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
