apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket
  template:
    metadata:
      labels:
        app: socket
    spec:
      containers:
        - name: socket
          image: akscr01sample.azurecr.io/socket:latest
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: socket-service
spec:
  selector:
    app: socket
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP  # Internal service (no external IP)
